apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: manufacturing-platform-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /manufacturing-creator(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: manufacturing-creator-svc
                port:
                  number: 8500

          - path: /multi-agent-manufacturing(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: multi-agent-manufacturing-svc
                port:
                  number: 8501

          - path: /main-app(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: main-app-svc
                port:
                  number: 8502